CF_RECAPTCHA_PUBLIC_KEY = 'recaptcha public key'
CF_RECAPTCHA_PRIVATE_KEY = 'recaptcha private key'

CF_XMPP_DOMAIN_NAME = 'ubuntu'
CF_HOST_DOMAIN_NAME = 'localhost'
CF_GUEST_FREE_MONEY = 100000

"""configuration values"""
CF_FREE_MONEY = 1000000
CF_ENCRYPTION_AES_KEY = 'aes encryption key'
CF_SECRET_SALT = 'secret salt'

CF_EMAIL_VERIFICATION_EXPIRED_TIME = 24*60*60*7 #1 week
CF_EMAIL_VERIFICATION_LIMIT_TIME = 60*60 #1 hour
CF_RESET_PASSWORD_EXPIRED_TIME = 60*60 #1 hour
CF_RESET_PASSWORD_LIMIT_TIME = 60*60 #1 hour
CF_EXCHANGE_RATE_CASH_MONEY = 1000

CF_SAFE_CAPTCHA_ACCESS_LIMIT_GLOBAL = 1000
CF_SAFE_CAPTCHA_ACCESS_LIMIT_IP = 5
CF_CAPTCHA_DEFAULT = 0

CF_SMTP_HOST = 'smtp host'
CF_SMTP_USER = 'user'
CF_SMTP_PASSWORD = 'password'

CF_WEBSERVICE_URL = "http://ubuntu/service"
CF_EMAIL_NOREPLY = "noreply@lacxingau.com"
CF_FACEBOOK_PREFIX = 'fb+'
CF_FACEBOOK_APPID = 'FB APPID'
CF_FACEBOOK_APPTOKEN = 'FB APPTOKEN'
