'''
Created on Mar 1, 2012

@author: leen
'''
#global config
USE_DATABASE = False #RAM only
USE_TIMEOUT = True#False
USE_ROOM_TYPE_LIST = False
ROOM_TYPE_LIST = [0, 5, 500, 1000, 2000, 5000, 10000]

#XMPP paramaters
XMPP_SERVICE_NAME ='game.ubuntu'
XMPP_SERVICE_PASSWORD = 'boxxgamexx'
XMPP_SERVICE_PORT = 8765
XMPP_SERVICE_HOST = '127.0.0.1'
XMPP_SERVICE_LOG = True
XMPP_DOMAIN_NAME = 'ubuntu'
#MSGQUEUE XMPP
MSGQUEUE_XMPP_PORT = 5000

#MSGQUEUE GAME
MSGQUEUE_GAME_PORT_INBOUND = 5001
MSGQUEUE_GAME_PORT_OUTBOUND = 5002


#Device XMPP
MSGQUEUE_XMPP_BIND_STRING = ['tcp://ubuntu:5000',]
MSGQUEUE_GAME_BIND_STRING_INBOUND = ['tcp://ubuntu:5001',]
MSGQUEUE_GAME_BIND_STRING_OUTBOUND = ['tcp://ubuntu:5002',]
#test comment
CHEAT_CODE_PASSWORD = 'howcanyousaythatbabyxyii*&'

#Game setting
TAX_RATE = 0.05
DEFAULT_FREE_MONEY = 1000000
DEFAULT_FREE_MONEY_TIME = 86400
EXCHANGE_RATE_CASH_MONEY = 1000
GUEST_ACCOUNT_EXPIRED_TIME = 24*60*60
#Game configuration
TLROOM_CONFIG_LUCKY_WIN = True
TLROOM_CONFIG_IMPRISON_PLAYER = True
TLROOM_CONFIG_ROTTEN_PIG = True
TLROOM_CONFIG_ANONYMOUS = True